# Generated by Django 5.2.3 on 2025-06-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('duration', models.PositiveIntegerField()),
                ('is_break', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pomodoro Session',
                'verbose_name_plural': 'Pomodoro Sessions',
            },
        ),
    ]
