# Generated by Django 5.2.3 on 2025-06-22 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pomodorosession',
            options={'verbose_name': 'pomodoro session', 'verbose_name_plural': 'pomodoro sessions'},
        ),
        migrations.AlterField(
            model_name='pomodorosession',
            name='completed',
            field=models.BooleanField(default=True, verbose_name='completed'),
        ),
        migrations.AlterField(
            model_name='pomodorosession',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='pomodorosession',
            name='is_break',
            field=models.BooleanField(default=False, verbose_name='is break'),
        ),
        migrations.AlterField(
            model_name='pomodorosession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='pomodorosession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
