# Generated by Django 5.2.3 on 2025-06-25 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0003_alter_pomodorosession_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DurationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('break', 'Break'), ('work', 'Work')], max_length=10, verbose_name='Duration')),
                ('minutes', models.PositiveIntegerField(default=0, verbose_name='Minutes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Duration',
                'verbose_name_plural': 'Durations',
            },
        ),
        migrations.AlterModelOptions(
            name='pomodorosession',
            options={'verbose_name': 'Pomodoro Session', 'verbose_name_plural': 'Pomodoro Sessions'},
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='pomodorosession',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_sessions', to='focus.durationcategory', verbose_name='Category'),
            preserve_default=False,
        ),
    ]
