# Generated by Django 5.2.3 on 2025-06-25 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0004_durationcategory_alter_pomodorosession_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pomodorosession',
            name='is_break',
        ),
    ]
