# Generated by Django 5.2.3 on 2025-06-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='users/pictures/image.png', upload_to='users/pictures', verbose_name='picture'),
        ),
    ]
