# Generated by Django 5.2.3 on 2025-06-22 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musictrack',
            options={'verbose_name': 'Music track', 'verbose_name_plural': 'Music tracks'},
        ),
        migrations.AlterModelOptions(
            name='purchasedmusic',
            options={'verbose_name': 'Purchased music', 'verbose_name_plural': 'Purchased musics'},
        ),
        migrations.AddField(
            model_name='musictrack',
            name='artist',
            field=models.CharField(default='artist', max_length=200, verbose_name='artist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='audio_file',
            field=models.FileField(upload_to='music/', verbose_name='audio_file'),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='price',
            field=models.PositiveIntegerField(verbose_name='price in coins'),
        ),
        migrations.AlterField(
            model_name='purchasedmusic',
            name='purchased_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='purchased at'),
        ),
        migrations.AlterField(
            model_name='purchasedmusic',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_music', to='marketplace.musictrack', verbose_name='track'),
        ),
        migrations.AlterField(
            model_name='purchasedmusic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_music', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
