# Generated by Django 5.2.3 on 2025-06-22 15:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cointransaction',
            options={'verbose_name': 'Coin transaction', 'verbose_name_plural': 'Coin transactions'},
        ),
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'ordering': ['score'], 'verbose_name': 'Leaderboard', 'verbose_name_plural': 'Leaderboards'},
        ),
        migrations.AlterModelOptions(
            name='medal',
            options={'verbose_name': 'Medal', 'verbose_name_plural': 'Medals'},
        ),
        migrations.RemoveField(
            model_name='medal',
            name='awarded_at',
        ),
        migrations.AddField(
            model_name='cointransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='medal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='amount',
            field=models.IntegerField(verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='reason',
            field=models.CharField(max_length=255, verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coins', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='type',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], max_length=10, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medals', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
